var data = [
	{
		'comp':'uploadFolder/TJOY/case_comp_TJOY.jpg',
		'full':[
			'uploadFolder/TJOY/case_package_TJOY01.jpg',
			'uploadFolder/TJOY/case_package_TJOY02.jpg'
		],
		'customer':'丁家宜',
		'agency':'上海西武百創廣告',
		'creativeDirector':'Penny',
		'artDirector':'Eseen',
		'workTime':'2013.02'
	},
	{
		'comp':'uploadFolder/lion/case_comp_lion_toothpaste.jpg',
		'full':[
			'uploadFolder/lion/case_package_lion_toothpaste01.jpg',
			'uploadFolder/lion/case_package_lion_toothpaste02.jpg'
		],
		'customer':'日本獅王',
		'agency':'上海西武百創廣告',
		'creativeDirector':'Penny',
		'artDirector':'Eseen',
		'workTime':'2013.07'
	},
	{
		'comp':'uploadFolder/xsx_package/case_comp_xsx_package.jpg',
		'full':[
			'uploadFolder/xsx_package/case_package_xsx01.jpg',
			'uploadFolder/xsx_package/case_package_xsx02.jpg',
			'uploadFolder/xsx_package/case_package_xsx03.jpg',
			'uploadFolder/xsx_package/case_package_xsx04.jpg',
			'uploadFolder/xsx_package/case_package_xsx05.jpg',
			'uploadFolder/xsx_package/case_package_xsx06.jpg',
			'uploadFolder/xsx_package/case_package_xsx07.jpg',
			'uploadFolder/xsx_package/case_package_xsx08.jpg'
		],
		'customer':'香尚香',
		'agency':'上海西武百創廣告',
		'creativeDirector':'Penny',
		'artDirector':'Eseen',
		'workTime':'2013.07'
	},
	{
		'comp':'uploadFolder/TJOY/case_comp_TJOY.jpg',
		'full':[
			'uploadFolder/TJOY/case_package_TJOY01.jpg',
			'uploadFolder/TJOY/case_package_TJOY02.jpg'
		],
		'customer':'丁家宜',
		'agency':'上海西武百創廣告',
		'creativeDirector':'Penny',
		'artDirector':'Eseen',
		'workTime':'2013.02'
	},
	{
		'comp':'uploadFolder/TJOY/case_comp_TJOY.jpg',
		'full':[
			'uploadFolder/TJOY/case_package_TJOY01.jpg',
			'uploadFolder/TJOY/case_package_TJOY02.jpg'
		],
		'customer':'丁家宜',
		'agency':'上海西武百創廣告',
		'creativeDirector':'Penny',
		'artDirector':'Eseen',
		'workTime':'2013.02'
	},
	{
		'comp':'uploadFolder/TJOY/case_comp_TJOY.jpg',
		'full':[
			'uploadFolder/TJOY/case_package_TJOY01.jpg',
			'uploadFolder/TJOY/case_package_TJOY02.jpg'
		],
		'customer':'丁家宜',
		'agency':'上海西武百創廣告',
		'creativeDirector':'Penny',
		'artDirector':'Eseen',
		'workTime':'2013.02'
	}
]